# Generated by Django 5.0.6 on 2024-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_roomscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomscores',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
