# Generated by Django 5.0.6 on 2024-08-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_roomscores_game_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomscores',
            name='life',
            field=models.IntegerField(default=3),
        ),
    ]
