# Generated by Django 5.0.6 on 2024-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_roomscores_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='match_ended',
            field=models.BooleanField(default=False),
        ),
    ]
